## Simple Convolution

In [ ]:
import numpy as np

input_matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

kernel = np.array([
    [1, 0],
    [-1, 1]
])

padding = 1
stride = 2
kernel_size = 2


def simple_conv2d(input_matrix: np.ndarray, kernel: np.ndarray, padding: int, stride: int):
    """
    [01,01] -> [12,01] -> [23,01]
    [01,12] -> [12,12] -> [23,12]
    [01,23] -> [12,23] -> [23,23]
    """
    input_height, input_width = input_matrix.shape
    kernel_size, _ = kernel.shape

    output_matrix = np.zeros((input_height, input_width))
    print(f'RAW:\n{output_matrix} \n')

    kernel = kernel[:kernel_size, :kernel_size] # count from 0, so use : to take value at index 0, 1 for row and column
    print('KERNEL: \n', kernel, '\n')

    # Your code here
    for row in range(input_height - 1):
        for col in range(input_width -1):
            stride = kernel_size + col + 1
            print(f'Conv Range: {row}:{stride} - {col}:{stride + 1}')

            matrix = input_matrix[row:stride + 1, col]
            print(f'MATRIX BEFORE:\n {matrix}')


            # out = np.dot(kernel, matrix) # 2x2 matrix
            # print(f'MATRIX AFTER \n{out}')
            # input_matrix[:stride, :stride] = out

            # output_matrix[stride:, :stride] = out
            # print(f'OUT >> {i} \n {output_matrix}\n')

    return output_matrix

output = simple_conv2d(input_matrix, kernel, padding, stride)
print(output)

RAW:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

KERNEL: 
 [[ 1  0]
 [-1  1]] 

Conv Range: 0:3 - 0:3
MATRIX BEFORE:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]
Conv Range: 0:4 - 1:4
MATRIX BEFORE:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Conv Range: 0:5 - 2:5
MATRIX BEFORE:
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
Conv Range: 1:3 - 0:3
MATRIX BEFORE:
 [[ 5  6]
 [ 9 10]]
Conv Range: 1:4 - 1:4
MATRIX BEFORE:
 [[ 5  6]
 [ 9 10]
 [13 14]]
Conv Range: 1:5 - 2:5
MATRIX BEFORE:
 [[ 5  6]
 [ 9 10]
 [13 14]]
Conv Range: 2:3 - 0:3
MATRIX BEFORE:
 [[ 9 10]]
Conv Range: 2:4 - 1:4
MATRIX BEFORE:
 [[ 9 10]
 [13 14]]
Conv Range: 2:5 - 2:5
MATRIX BEFORE:
 [[ 9 10]
 [13 14]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
input_matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

"""
01,01 -> 12,01 -> 23,01
01,12 -> 12,12 -> 24,13
01,23 -> 12,23 -> 23,23
"""

print(input_matrix[2:4, 1:3])

[[10 11]
 [14 15]]
