Code xong đóng tiền học

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.0+cu118


In [4]:
device = torch.device('cuda' if torch.cuda.is_available() else 'gpu')
print('current device ', device)

current device  cuda


In [5]:
tensor = torch.randn(10, 10)
tensor_on_device = tensor.to(device)
print(tensor_on_device.device) # 0 mean using is the first prioritize

cuda:0


In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [8]:
x_ones = torch.ones_like(x_data)
print(f"Ones tensor: \n {x_ones} \n")

x_ones = torch.zeros_like(x_data)
print(f"Zero tensor: \n {x_ones} \n")

Ones tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Zero tensor: 
 tensor([[0, 0],
        [0, 0]]) 



In [9]:
shape = (2, 3, )
rand_tensor = torch.rand(shape) # create random number
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.8844, 0.3451, 0.2813],
        [0.2881, 0.0779, 0.5951]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Operations on Tensor

There are over 1200 tensor operations, including arithmetic, linear algebra, matrix manipulation (tranposing, indexing, slicing), samplings and more. 

By default, tensor are created and stores on the CPU. We need to explicitly more tensors to the accelerator using `.to` method. 

In [11]:
import torch.accelerator

if torch.accelerator.is_available():
	accelarator = torch.accelerator.current_accelerator()
	tensor = tensor.to(accelarator)
	print('current accelarator:', accelarator)

current accelarator: cuda


In [12]:
# from torch import nn
# from torch.utils.data import DataLoader
# from torchvision import datasets
# from torchvision.transforms import ToTensor

# # Download training data from open datasets.
# training_data = datasets.FashionMNIST(
#     root="data",
#     train=True,
#     download=True,
#     transform=ToTensor(),
# )

# # Download test data from open datasets.
# test_data = datasets.FashionMNIST(
#     root="data",
#     train=False,
#     download=True,
#     transform=ToTensor(),
# )

In [13]:
from sklearn.datasets import load_iris
from torch.utils.data import TensorDataset, DataLoader

iris=load_iris()
X = torch.tensor(iris.data, dtype=torch.float32) # shape (150, 4)
y = torch.tensor(iris.data, dtype=torch.long) # class labels 0, 1, 2



In [14]:
batch_size = 16

# Create a Dataset and DataLoader for training/validation split
dataset = TensorDataset(X, y)
train_loader = DataLoader(dataset, batch_size=16, shuffle=True)

print(len(train_loader))

10


In [16]:
for X, y in train_loader:
	"""
 		N: Number of images in the batch
		C: Number of channels in the image (e.g., 1 for grayscale, 3 for RGB)
		H: Height of the image
		W: Width of the image
	"""
	print(f"Shape of X [N, C, H, W]: {X.shape}")
	print(f"Shape of y: {y.shape} {y.dtype}")
	break

Shape of X [N, C, H, W]: torch.Size([16, 4])
Shape of y: torch.Size([16, 4]) torch.int64


In [ ]:
class Animal:
 	def __init__(self, animal, breed):
		self.animal = animal
		self.breed = breed
		
	def __str__(self):
		return "You just called __str__" # display information in print

	def __repr__(self): #? repr mean string representation
     	# also display information in print if __str__ is not define
		# display raw information
  		return "You just called __repr__" 

a = Animal("Cat", "Three eyes")
print(a)

a

You just called __repr__


You just called __repr__

In [ ]:
def

In [ ]:
class NeuralNet(nn.Module):
    def __init__(self):
        #? Store the state of a NeuralNet Object. We can define many Object using this single class
        super().__init__() # inherit pytorch nn library
        
        