In [ ]:
import numpy as np

#? It is similar to Python's built-in range() function but returns a NumPy array instead of a list,
#? making it more suitable for numerical computations and array-based operations
data = np.arange(1, 3, 0.5) # start, stop, step
print(data)

[1.  1.5 2.  2.5]


In [62]:
d = np.arange(10)
print(d)
d.reshape(-1, 5)

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [20]:
import numpy as np

data = np.arange(6)
print(data)

data = data.copy().reshape(2, 3)

# np.repeat(data, 3)
data[:, 1]

[0 1 2 3 4 5]


array([1, 4])

In [21]:
data = np.arange(6)
print(data)


[0 1 2 3 4 5]


In [22]:
data[data >= 3]

array([3, 4, 5])

In [ ]:
data = np.arange(9).reshape(3, 3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
data = data.copy()[:, [1,0,2]] # row, column
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
data[:, :-1] # cutoff column at position/index -1

array([[0, 1],
       [3, 4],
       [6, 7]])

In [45]:
data = np.arange(9).reshape(3, 3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
data[:2, 1:]*3 # from row (up to down) to coumn (left to right)

array([[ 3,  6],
       [12, 15]])

In [ ]:
import numpy as np
arr = np.array([2,1,5,8,5,9])
np.sum(arr == 5)

np.int64(2)

In [ ]:
arr = np.array([2,1,5,8,5,9])
# delete 1 from arr
np.delete(arr, np.arange(1, 2)) #? np.arrange(1, 2) return 1

array([2, 5, 8, 5, 9])

In [ ]:
arr = np.array([2,1,5,8,5,9])
del_indices = np.where(arr==5)[0] #? return position of every '5' inside the array
print(del_indices) #? delete element at position 2 and 4
print(np.delete(arr, 2))

[2 4]
[2 1 8 9]


In [27]:
arr = np.array([[4,5,6]])
for i, v in np.ndenumerate(arr):
    print(i, v)

(0, 0) 4
(0, 1) 5
(0, 2) 6


In [ ]:
arr = np.array([[4,5,6], [8,8,8], [9,9,0]])
for i, v in np.ndenumerate(arr):
    print(i, v)

(0, 0) 4
(0, 1) 5
(0, 2) 6
(1, 0) 8
(1, 1) 8
(1, 2) 8
(2, 0) 9
(2, 1) 9
(2, 2) 0


In [1]:
import numpy as np

arr = np.array([[1, 2, 1],
                [3, 1, 2],
                [3, 3, 1]])

element_counts = {}
for row in arr:
    for element in row:
        element_counts[element] = element_counts.get(element, 0) + 1

print(element_counts)

{np.int64(1): 4, np.int64(2): 2, np.int64(3): 3}
