### Convolution without Padding and Stride

In [ ]:
import numpy as np

input_matrix = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

kernel = np.array([
    [1, 0],
    [-1, 1]
])

padding = 1
stride = 2

def simple_conv2d(input_matrix, kernel, padding, stride):
    """A simple Convolution function
    Note: copy input_matrix as output_matrix so we not modify the original matrix
    1. get input matrix and kernel width and height
    2. figure a way to slides NxN submatrix within input matrix by adding "Kernel Size by Index"
    3. Multiply Slides Matrix by Kernel
    4. Update sliced values to the output Matrix
    """

    matrix_height, matrix_width = input_matrix.shape
    kernel_size, _ = kernel.shape
    output_matrix = input_matrix.copy()

    # Multiply Conv.Kernel
    for row in range(matrix_height - 1):
        # print(f"ROW - {row}")
        for col in range(matrix_width - 1):
            # print('INDEX - ', col)
            # change to output matrix bc it local value change with the loop
            conv = output_matrix[row:row+kernel_size, col:col+kernel_size] # row 0 to 4
            # print('Conv Before\n', conv)
            output_matrix[row:row+kernel_size, col:col+kernel_size] = conv @ kernel
            # print('Conv After\n', output_matrix, '\n')

    return output_matrix

# [[ -1  -1  -1   4]
#  [  0   0  -9   8]
#  [  0   0 -13  12]
#  [ -1  -1  -1  16]]
output = simple_conv2d(input_matrix, kernel, padding, stride)
print(output)

[[ -1  -1  -1   4]
 [  0   0  -9   8]
 [  0   0 -13  12]
 [ -1  -1  -1  16]]


### Convolution with Padding and Stride

In [48]:
import numpy as np

input_matrix = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

kernel = np.array([
    [1, 0],
    [-1, 1]
])

padding = 1
stride = 1

def simple_conv2d(input_matrix: np.matrix, kernel: np.matrix, padding: int, stride:int) -> np.matrix:
    """A simple Convolution function
    Note: copy input_matrix as output_matrix so we not modify the original matrix
    1. get input matrix and kernel width and height
    2. figure a way to slides NxN submatrix within input matrix by adding "Kernel Size by Index"
    3. Multiply Slides Matrix by Kernel
    4. Update sliced values to the output Matrix
    5. Stride: Moving whole submatrix N step at a time, after the 1st step, the question is How to increase all values at the same time. The submatrix influence by row and col thus, jsut add stride to row and col each iteration.
    6. Padding: Adding Zeros margin to the matrix -> Reverse thinking: Crease a Zeros matrix "N+1 by N+1" then integrate the original matrix to it
    """
    matrix_height, matrix_width = input_matrix.shape
    kernel_size, _ = kernel.shape
    output_matrix = np.zeros((matrix_height + padding*2, matrix_width + padding*2))
    output_matrix[padding:matrix_height+padding, padding:matrix_width+padding] = input_matrix
    print(f"ORIGINAL:\n {output_matrix}, {output_matrix.shape}\n")

    # Multiply Conv.Kernel
    for row in range(matrix_height - stride):
        #? Apply Stride at second step only
        if row > 0:
            row = row + stride - 1

        print(f"ROW - {row}")
        for col in range(matrix_width - stride):
            if col > 0:
                col = col + stride - 1

            print('INDEX - ', col)
            # change to output matrix bc it local value change with the loop
            conv = output_matrix[row:row+kernel_size, col:col+kernel_size] # row 0 to 4
            print('Conv Before\n', conv)
            # output_matrix[row:row+kernel_size, col:col+kernel_size] = conv @ kernel
            # print('Conv After\n', output_matrix, '\n')

    return output_matrix


# [[ 1.  1. -4.],
# [ 9.  7. -4.],
# [ 0. 14. 16.]]
output = simple_conv2d(input_matrix, kernel, padding, stride)
print(output)

ORIGINAL:
 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  0.]
 [ 0.  5.  6.  7.  8.  0.]
 [ 0.  9. 10. 11. 12.  0.]
 [ 0. 13. 14. 15. 16.  0.]
 [ 0.  0.  0.  0.  0.  0.]], (6, 6)

ROW - 0
INDEX -  0
Conv Before
 [[0. 0.]
 [0. 1.]]
INDEX -  1
Conv Before
 [[0. 0.]
 [1. 2.]]
INDEX -  2
Conv Before
 [[0. 0.]
 [2. 3.]]
ROW - 1
INDEX -  0
Conv Before
 [[0. 1.]
 [0. 5.]]
INDEX -  1
Conv Before
 [[1. 2.]
 [5. 6.]]
INDEX -  2
Conv Before
 [[2. 3.]
 [6. 7.]]
ROW - 2
INDEX -  0
Conv Before
 [[0. 5.]
 [0. 9.]]
INDEX -  1
Conv Before
 [[ 5.  6.]
 [ 9. 10.]]
INDEX -  2
Conv Before
 [[ 6.  7.]
 [10. 11.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  0.]
 [ 0.  5.  6.  7.  8.  0.]
 [ 0.  9. 10. 11. 12.  0.]
 [ 0. 13. 14. 15. 16.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [ ]:
import numpy as np

input_matrix = np.array([
    [1,  2,  3,  4],
    [5,  6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

kernel = np.array([
    [1, 0],
    [-1, 1]
])

padding = 1
stride = 2

def simple_conv2d(input_matrix: np.matrix, kernel: np.matrix, padding: int, stride:int) -> np.matrix:
    """A simple Convolution function
    Note: copy input_matrix as output_matrix so we not modify the original matrix
    1. get input matrix and kernel width and height
    2. figure a way to slides NxN submatrix within input matrix by adding "Kernel Size by Index"
    3. Multiply Slides Matrix by Kernel
    4. Update sliced values to the output Matrix
    5. Stride: Moving whole submatrix N step at a time, after the 1st step, the question is How to increase all values at the same time. The submatrix influence by row and col thus, jsut add stride to row and col each iteration.
    6. Padding: Adding Zeros margin to the matrix -> Reverse thinking: Crease a Zeros matrix "N*2 by N*2" (*2 because it square, think about it) then integrate the original matrix to it then shift the original position from (0, 0) to (0 + padding, 0 + padding) for centering
    7. Calculate output_matrix
    """
    matrix_height, matrix_width = input_matrix.shape
    kernel_size, _ = kernel.shape
    origin_matrix = np.zeros((matrix_height + padding*2, matrix_width + padding*2))
    origin_matrix[padding:matrix_height+padding, padding:matrix_width+padding] = input_matrix
    print(f"ORIGINAL:\n {origin_matrix}, {origin_matrix.shape}\n")
    print(f'KERNEL\n', kernel, '\n')

    # calculate Conv output shape which base on Matrix "width & height" influenced by "kernel size (substract), padding (add), stride (substract)"
    output_matrix = np.zeros((
        np.ceil(((matrix_height - kernel_size + 2*padding) + 1) / stride).astype('int'),
        np.ceil(((matrix_width - kernel_size + 2*padding) + 1) / stride).astype('int'),
    )) # np.zeros() require int so must use astype('int')
    print(f'OUT SHAPE - Padding {padding} - Stride {stride} \n', output_matrix, output_matrix.shape)

    # Multiply Conv.Kernel
    for row in range(matrix_height - stride):
        #? Apply Stride at second step only
        if row > 0:
            row = row + stride - 1
        print(f'\nROW {row}')

        for col in range(matrix_width - stride):
            if col > 0:
                col = col + stride - 1

            conv = origin_matrix[row:row+kernel_size, col:col+kernel_size] # row 0 to 4
            print('CONV:\n', conv)

            #? ElementWise(Conv * Kernel)
            conv_out = conv * kernel # element-wise multiplication
            print(f'{col} - Conv*Kernel:\n', conv_out)
            conv_out = np.sum(conv_out) # element-wise multiplication
            print(f'{col} - Sum(Conv*Kernel):\n', conv_out)
            output_matrix[row, col] = conv_out
            

    return output_matrix

# [[ 1.  1. -4.],
# [ 9.  7. -4.],
# [ 0. 14. 16.]]
output = simple_conv2d(input_matrix, kernel, padding, stride)
print('OUTPUT:\n', output, output.shape)

ORIGINAL:
 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  0.]
 [ 0.  5.  6.  7.  8.  0.]
 [ 0.  9. 10. 11. 12.  0.]
 [ 0. 13. 14. 15. 16.  0.]
 [ 0.  0.  0.  0.  0.  0.]], (6, 6)

KERNEL
 [[ 1  0]
 [-1  1]] 

OUT SHAPE - Padding 1 - Stride 2 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3)

ROW 0
CONV:
 [[0. 0.]
 [0. 1.]]
0 - Conv*Kernel:
 [[ 0.  0.]
 [-0.  1.]]
0 - Sum(Conv*Kernel):
 1.0
CONV:
 [[0. 0.]
 [2. 3.]]
2 - Conv*Kernel:
 [[ 0.  0.]
 [-2.  3.]]
2 - Sum(Conv*Kernel):
 1.0

ROW 2
CONV:
 [[0. 5.]
 [0. 9.]]
0 - Conv*Kernel:
 [[ 0.  0.]
 [-0.  9.]]
0 - Sum(Conv*Kernel):
 9.0
CONV:
 [[ 6.  7.]
 [10. 11.]]
2 - Conv*Kernel:
 [[  6.   0.]
 [-10.  11.]]
2 - Sum(Conv*Kernel):
 7.0
OUTPUT:
 [[1. 0. 1.]
 [0. 0. 0.]
 [9. 0. 7.]] (3, 3)


In [88]:
m = np.array([[0,  0], [-1,  1]])
np.sum(m)

np.int64(0)